import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/Providers";

import { Bricolage_Grotesque } from "next/font/google";
import { Libre_Franklin } from "next/font/google";
import { cn } from "@/lib/utils";
import { TailwindIndicator } from "@/components/tailwind-indicator";

const caudex = Bricolage_Grotesque({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-grotesque",
  weight: ["400", "700", "800", "600", "500", "300", "200"],
});
const libre_franklin = Libre_Franklin({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-libre_franklin",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className={cn(caudex.variable, libre_franklin.variable)}>
        <Providers>{children}</Providers>
        <TailwindIndicator />
      </body>
    </html>
  );
}
